In [1]:
import gym
import numpy as np

In [2]:
env = gym.make('FrozenLake-v0')

In [179]:
env.reset()
env.render()


SFFF
FHFH
FFFH
HFFG


In [25]:
policy = np.random.randint(0,4,env.observation_space.n)
#policy = np.ones(env.observation_space.n)
alpha = 0.05
discount = 0.8

In [26]:
policy

array([2, 3, 2, 2, 1, 1, 2, 0, 0, 0, 1, 3, 2, 1, 2, 2])

In [27]:
def iterate_td(env, policy, alpha, discount, iters = 100000):
    # initialize value array
    value_array = np.zeros(env.observation_space.n)
    
    # run policy and update V
    state = env.reset()
    for t in range(iters):
        action = policy[state]
        next_state, reward, end, _ = env.step(action)
        #alpha = 2*(t**eta)
        
        value_array[state] += alpha * (reward + discount * (value_array[next_state] - value_array[state]))
        if end:
            state = env.reset()
        else:
            state = next_state
        
    return(value_array)

In [28]:
td_value = iterate_td(env, policy, alpha = 0.01, discount = .8, iters = 2000000)

In [29]:
td_value.reshape(4,4)

array([[0.02036965, 0.03978704, 0.06319078, 0.        ],
       [0.        , 0.        , 0.13564327, 0.        ],
       [0.        , 0.12470431, 0.34272144, 0.        ],
       [0.        , 0.40633113, 0.79194273, 0.        ]])

In [207]:
def iterate_evmc(env, policy, alpha, discount, iters = 100000):
    # initialize value array
    value_array = np.zeros(env.observation_space.n)
    
    # run policy and update V
    for _ in range(iters):
        # Run Episode
        state = env.reset()
        ep_state = []
        ep_reward = []
        end = False
        while not end:
            action = policy[state]
            next_state, reward, end, _ = env.step(action)
            ep_state.append(state)
            ep_reward.append(reward)
            state = next_state
        # Update Value Fxn
        sum_r = 0
        for t in range(len(ep_state)):
            state = ep_state[-(t+1)]
            sum_r += ep_reward[-(t+1)] + discount * sum_r
            value_array[state] += alpha * (sum_r - value_array[state])
            
    return(value_array)

In [208]:
ev_value = iterate_evmc(env, policy, alpha = 0.01, discount = .8, iters = 1000000)

In [204]:
ev_value.reshape(4,4)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])